services:
  uakino.club_bot:
    container_name: uakino.club_bot
    restart: always
    image: uakino.club_bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Europe/Kiev
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./db
        target: /app/db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org')"]
      interval: 30s
      timeout: 10s
      retries: 3
